[[pages]]
path = "pages/homepage.py"
name = "Home"
icon = "📄"

[[pages]]
path = "pages/dashboard.py"
name = "Area do Professor"
icon = "🎓"

[[pages]]
path = "pages/treinamentos_gratuitos.py"
name = "Treinamentos gratuitos (Samples)"
icon = "📚"
