[[pages]]
path = "pages/homepage.py"
name = "Home"
icon = "📄"

[[pages]]
path = "pages/treinamentos_gratuitos.py"
name = "Treinamentos gratuitos"
icon = ":bar_chart:"


[[pages]]
path = "pages/dashboard.py"
name = "Treinamentos completos"
icon = ":bar_chart:"